# Site settings
title: "CV Ruoming"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Ruoming Peng"
resume_title:                   "Postdoc Fellow"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "pruoming@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "+49 1627301503"
resume_contact_address:         "Stuttgart"

resume_header_contact_info:     "Stuttgart • 49-1627301503 • pruoming@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: "<p>Ruoming is from Huangshi (China) which is a city located in southeastern Hubei province, primarily along the southwestern bank of the Yangtze River. He received a bachelor's degree in Microelectronics from the University of Electronic Science and Technology of China. In 2015, Ruoming started the journey of the Ph.D. in Electrical Engineering at the University of Minnesota under the supervision of Prof. Mo Li and then transferred with the Li group to the University of Washington in 2018. He has developed broad interests in semiconductor physics especially 2D semiconductors including black Phosphorus and TMDCs during his Ph.D. career. Ruoming was awarded Clairmont L. Egtvedt Endowed Engineering Fellowship in 2020 and also the Materials Research Society travel grant in 2021. After graduation, Ruoming join the University of Chicago as the postdoc fellow and then move to 3rd Institute of Physics at Stuttgart University under the supervision of prof. Jörg Wrachtrup. Ruoming has developed strong interests in quantum sensing and quantum communication. He is now working on the scanning NV probe technique for condensed matter physics, and also developing integrated quantum photonic devices based on diamond and SiC.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url:            "https://github.com/jglovier/resume-template"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/ruoming-peng-55a629ab/"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "pruoming.github.io"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
